name: quill_delta
description: Simple and expressive format for describing rich-text content created for Quill.js editor. This package is unofficial port to Dart from JavaScript.
version: 3.0.0-nullsafety.2
homepage: https://github.com/pulyaevskiy/quill-delta-dart
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  collection: ^1.15.0
  quiver: ^3.0.0
  diff_match_patch:
    git:
      url: https://github.com/superlistapp/diff-match-patch.git
      ref: 18a741c598300be06d96d91422279e607dc447c6

dev_dependencies:
  coverage: ^1.0.0
  pedantic: ^1.11.0
  test: ^1.17.5
